discover:
  use_type: etcd
  dial_timeout: 5
  endpoints:
    - "127.0.0.1:2379"
rpcx:
   use_type: nats
   dial_timeout: 5
   endpoints:
     - "nats://127.0.0.1:4222"
stores:
    use_type: redis
    dial_timeout: 5
    password: ""
    db: 0
    endpoints:
      - "127.0.0.1:6379"
